// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore.Dados.Contexto;

namespace NetCore.Dados.Migrations
{
    [DbContext(typeof(ContextoDB))]
    [Migration("20181029171746_ConfiguracaoCampos")]
    partial class ConfiguracaoCampos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCore.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCategoria")
                        .HasColumnType("varchar")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("NetCore.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("varchar")
                        .HasMaxLength(14);

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Cep")
                        .HasColumnType("varchar")
                        .HasMaxLength(100);

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar")
                        .HasMaxLength(100);

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("varchar")
                        .HasMaxLength(125);

                    b.Property<string>("Estado")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .HasColumnType("varchar")
                        .HasMaxLength(125);

                    b.Property<int?>("Numero");

                    b.Property<string>("Rua")
                        .HasColumnType("varchar")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("NetCore.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("NetCore.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
